CREATE TABLE CLIENTE(
  ID_CLIENTE NUMERIC(10,0) NOT NULL PRIMARY KEY,
  RAZON_SOCIAL VARCHAR2(240) NOT NULL UNIQUE,
  RUC CHAR(11) NOT NULL UNIQUE,
  DIRECCION VARCHAR2(280) NOT NULL,
  ESTADO CHAR(1) DEFAULT '1'
);

CREATE TABLE TALLER(
  ID_TALLER NUMERIC(10,0) NOT NULL PRIMARY KEY,
  NOMBRE VARCHAR2(240) NOT NULL UNIQUE,
  DESCRIPCION VARCHAR2(4000) NOT NULL,
  ESTADO CHAR(1) DEFAULT '1'
);

INSERT INTO CLIENTE(ID_CLIENTE,RAZON_SOCIAL,RUC, DIRECCION) VALUES (1,'GALAXY TRAINING','20544987306','AV. AREQUIPA 330 OFI. 801');
INSERT INTO CLIENTE(ID_CLIENTE,RAZON_SOCIAL,RUC, DIRECCION) VALUES (2,'TELEFONICA DEL PERU S.A.','20100017491','Av. Juan de Arona N° 786');
COMMIT;
SELECT * FROM CLIENTE;




CREATE TABLE AUTOS(
  codigo NUMERIC(10,0) NOT NULL PRIMARY KEY,
  placa VARCHAR2(240) NOT NULL UNIQUE,
  ano  NUMERIC(10,0) NOT NULL UNIQUE,
  modelo VARCHAR2(280) NOT NULL,
  marca VARCHAR2(280) NOT NULL,
  estado CHAR(1) DEFAULT '1'
);



INSERT INTO AUTOS (codigo,placa,ano,modelo,marca,estado) VALUES (1,'ALV169',2018,'ELANTRA','HYUNDAI',1);
INSERT INTO AUTOS (codigo,placa,ano,modelo,marca,estado) VALUES (2,'JLV168',2016,'TUCSON','HYUNDAI',1);
INSERT INTO AUTOS (codigo,placa,ano,modelo,marca,estado) VALUES (3,'HLV167',2015,'SANTA FE','HYUNDAI',1);
INSERT INTO AUTOS (codigo,placa,ano,modelo,marca,estado) VALUES (4,'GLV166',2014,'COROLA','TOYOA',1);
COMMIT;

CREATE TABLE usuarios(
  id_user NUMERIC(10,0) NOT NULL PRIMARY KEY,
  usuario VARCHAR2(240) NOT NULL UNIQUE,
  clave VARCHAR2(280) NOT NULL,
  estado CHAR(1) DEFAULT '1'
);

INSERT INTO usuarios (id_user,usuario,clave) VALUES (1,'JG','123');
INSERT INTO usuarios (id_user,usuario,clave) VALUES (2,'JGS','123');
COMMIT;

