create or replace
PACKAGE PKG_TALLER AS 

  TYPE C_CURSOR IS REF CURSOR;
   
  PROCEDURE SP_LISTAR(
    P_C_CURSOR OUT C_CURSOR,
    P_NOMBRE IN TALLER.NOMBRE%TYPE
  );
  
  PROCEDURE SP_INSERTAR(
    P_ID_TALLER     OUT TALLER.ID_TALLER%TYPE,
    P_NOMBRE        IN  TALLER.NOMBRE%TYPE,
    P_DESCRIPCION   IN  TALLER.DESCRIPCION%TYPE
  );
  
END PKG_TALLER;