CREATE SEQUENCE SEQ_CLIENTE START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_TALLER START WITH 4 INCREMENT BY 1;

CREATE SEQUENCE SEQ_AUTOS START WITH 1 INCREMENT BY 1;

SELECT SEQ_AUTOS.NEXTVAL FROM DUAL;